name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package manager
      run: corepack enable && corepack install
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
    - uses: actions/upload-artifact@v4
      with:
        name: qlocktwo-${{ matrix.node-version }}
        path: dist/*
